In [1]:
from petl import look, fromdb, fromjson,  unpackdict, fromdicts, cut, rename, tocsv
from pandas import DataFrame
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import csv
import csv as reader
import sqlite3 as sql
import psycopg2 as pc
import mysql.connector 
import requests, urllib, json
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
# ANGELO LOUIS L. HIZON
df1 = pd.read_csv('finals_diabetes_data - diabetes_data1.csv')
df1.head()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
0,1,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,2,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,3,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,4,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,5,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [3]:
df1.tail()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
95,96,56,Female,Yes,Yes,No,Yes,No,No,Yes,Yes,No,No,Yes,No,No,No,Positive
96,97,30,Female,Yes,Yes,Yes,Yes,No,No,No,Yes,No,Yes,Yes,Yes,No,No,Positive
97,98,31,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,No,Yes,Yes,No,No,Positive
98,99,35,Female,Yes,Yes,No,No,No,No,Yes,No,No,No,No,No,Yes,No,Positive
99,100,39,Female,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,Yes,Yes,No,No,No,Positive

In [4]:
# ANGELO LOUIS L. HIZON
path = 'https://drive.google.com/uc?export=download&id=1Kxo3Oi-uFYCrev0mAMCvYleyFBTxNyrg'

In [5]:
df2 = pd.read_csv(path)
df2.head()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
0,101,48,Female,Yes,Yes,Yes,No,Yes,Yes,No,No,Yes,Yes,No,Yes,Yes,Yes,Positive
1,102,85,Male,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,Positive
2,103,90,Female,No,Yes,Yes,No,No,Yes,Yes,Yes,No,No,No,Yes,Yes,No,Positive
3,104,72,Male,Yes,No,Yes,Yes,Yes,No,No,No,Yes,Yes,Yes,Yes,Yes,No,Positive
4,105,70,Male,Yes,No,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,Yes,No,Positive

In [6]:
df2.tail()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
95,196,31,Male,Yes,No,No,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Positive
96,197,66,Male,No,No,No,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Positive
97,198,61,Female,Yes,No,No,No,Yes,No,No,No,Yes,No,No,No,Yes,No,Positive
98,199,58,Female,Yes,No,Yes,No,Yes,No,No,No,Yes,No,No,Yes,No,Yes,Positive
99,200,69,Female,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,No,No,Yes,No,Yes,Positive

In [7]:
# ANGELO LOUIS L. HIZON
sqlite_conn = sql.connect('DIA_SQLITE.db')

In [8]:
sqlite_c = sqlite_conn.cursor()

In [9]:
csv1 = pd.read_csv('finals_diabetes_data - diabetes_data3.csv')

In [10]:
csv1.to_sql(name = 'DIA3', con = sqlite_conn, index = False, if_exists='replace')

In [11]:
df3 = pd.read_sql_query("SELECT * FROM DIA3", sqlite_conn)
df3.head()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
0,201,40,Male,No,Yes,Yes,Yes,No,No,Yes,Yes,No,No,Yes,Yes,No,No,Negative
1,202,28,Male,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,Negative
2,203,37,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative
3,204,34,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative
4,205,30,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [12]:
df3.tail()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
95,296,55,Female,Yes,Yes,Yes,Yes,No,No,Yes,No,No,No,Yes,No,No,Yes,Positive
96,297,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,Yes,No,No,No,Positive
97,298,55,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
98,299,39,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive
99,300,43,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive

In [13]:
# ANGELO LOUIS L. HIZON
postgres_conn = pc.connect("""
    dbname = DIA_POSTGRES
    host = localhost
    user = postgres
    password = @Ngelo8998
""")

In [14]:
postgres_c = postgres_conn.cursor()

In [15]:
postgres_engine = create_engine('postgresql+psycopg2://postgres:@Ngelo8998@localhost:5432/DIA_POSTGRES')

In [16]:
csv2 = pd.read_csv('finals_diabetes_data - diabetes_data4.csv')

In [17]:
csv2.to_sql('DIA4', postgres_engine, index = False, if_exists = 'replace')

In [18]:
query = """
    SELECT * FROM "DIA4"
"""

df4 = pd.read_sql_query(query, postgres_conn)
df4.head()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
0,301,35,Female,Yes,Yes,No,Yes,No,No,Yes,No,No,No,No,No,No,No,Positive
1,302,47,Female,No,No,Yes,Yes,Yes,No,No,No,No,No,No,Yes,No,No,Positive
2,303,61,Female,Yes,No,No,No,Yes,No,No,No,Yes,No,No,No,Yes,No,Positive
3,304,58,Female,Yes,No,Yes,No,Yes,No,No,No,Yes,No,No,Yes,No,Yes,Positive
4,305,69,Female,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,No,No,Yes,No,Yes,Positive

In [19]:
df4.tail()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
45,346,58,Female,Yes,No,Yes,No,Yes,No,No,No,Yes,No,No,Yes,No,Yes,Positive
46,347,69,Female,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,No,No,Yes,No,Yes,Positive
47,348,40,Male,No,Yes,Yes,Yes,No,No,Yes,Yes,No,No,Yes,Yes,No,No,Negative
48,349,28,Male,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,Negative
49,350,37,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [20]:
# ANGELO LOUIS L. HIZON
mysql_conn = mysql.connector.connect(
    user = 'root',
    database = 'dia_mysql',
    password = '@Ngelo8998',
    host = 'localhost'
)

In [21]:
mysql_c = mysql_conn.cursor()

In [22]:
mysql_engine = create_engine('mysql+mysqlconnector://root:@Ngelo8998@localhost:3306/dia_mysql')

In [23]:
csv3 = pd.read_csv('finals_diabetes_data - diabetes_data5.csv')

In [24]:
# LOWER CASED THE TABLE NAME BECAUSE DB WONT ACCEPT UPPERCASED TABLE NAME
csv3.to_sql('dia5', mysql_engine, index = False, if_exists = 'replace')

In [25]:
df5 = pd.read_sql_query("SELECT * FROM dia5", mysql_conn)
df5.head()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
0,351,34,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative
1,352,30,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative
2,353,67,Male,Yes,No,No,Yes,Yes,No,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Negative
3,354,60,Male,No,No,No,Yes,No,No,No,No,No,No,Yes,Yes,No,No,Negative
4,355,58,Male,No,No,No,No,Yes,No,No,Yes,No,Yes,No,No,Yes,Yes,Negative

In [26]:
df5.tail()

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
160,511,67,Male,No,No,No,Yes,No,No,No,Yes,No,Yes,No,No,Yes,No,Negative
161,512,66,Male,No,No,No,Yes,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Yes,No,Negative
162,513,43,Male,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,Negative
163,514,62,Female,Yes,Yes,Yes,Yes,No,No,Yes,No,No,No,Yes,No,No,Yes,Positive
164,515,54,Female,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,Yes,No,No,No,Positive

In [27]:
# ANGELO LOUIS L. HIZON
with open('finals_diabetes_data - diabetes_data6.json') as fp:
    data = json.load(fp)

In [28]:
df6 = pd.DataFrame(data)
df6

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
0,516,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
1,517,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive
2,518,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
3,519,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
4,520,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [34]:
# ANGELO LOUIS L. HIZON
dataframe = pd.concat([df1,df2,df3,df4,df5,df6])
dataframe = dataframe.reset_index()
dataframe = dataframe.drop(['index'], axis=1)
dataframe = dataframe.drop_duplicates()
dataframe

,patient_id,age,gender,polyuria,polydipsia,sudden_weight_loss,weakness,polyphagia,genital_thrush,visual_blurring,itching,irritability,delayed_healing,partial_paresis,muscle_stiffness,alopecia,obesity,class
0,1,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,2,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,3,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,4,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,5,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,516,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
516,517,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive
517,518,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,519,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,520,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [35]:
dataframe.to_csv('complete.csv', index=False)

In [36]:
csv4 = pd.read_csv('complete.csv')

In [ ]:
csv4.to_sql('complete_dataset', mysql_engine, index = False, if_exists = 'replace')

In [ ]:
df7 = pd.read_sql_query("SELECT * FROM complete_dataset", mysql_conn)
df7.head()